version: '3'
services:
  wrattler_aiassistants:
    container_name: wrattler_wrattler_aiassistants_1
    build:
      context: aiassistants
      dockerfile: Dockerfile
    ports:
    - "5050:5050"
    volumes:
    - ./aiassistants/assistants:/app/assistants
    environment:
    - DATASTORE_URI=http://wrattler_wrattler_data_store_1:7102
    networks:
    - wrattler_nw

networks:
  wrattler_nw:
    driver: bridge
